### ISSUE TITLE
Reorganize UI

### ISSUE THREAD

**Issue by perfectstrong** [perfectstrong/MeshIneBits#24]
The toolbar and buttons should be rearranged in order to be more intuitive.

* Menu bar:
    * File
    * Model
    * Configuration
    * Pattern
    * View
    * Help
* Toolbar:
    * Slicer
    * Template:
        * Bit options
        * Layer options
        * Pattern
        * Pattern parameters
    * Auto-optimizer
* Review:
    * Display options
    * Selected slice
    * Replace bit

Between toolbar and status bar (in the bottom), there would be a logger.

**Comment by perfectstrong** [comment]
The program should focus on one window with 2D view integrated inside main window. The 3D view is optional to review at last or modify model at first.

**Comment by ChrisdAutume** [comment]
Hello @perfectstrong ,

Did you plan to make the config form ? Or should I submit one ?, I need this for the scheduler config  ...
